name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      run: 'docker buildx build --platform linux/arm64,linux/amd64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7 . -t finwo/adminer:latest -t finwo/adminer:4 -t finwo/adminer:4.8 -t finwo/adminer:4.8.1 --output=type=registry'

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     platforms: linux/amd64,linux/arm64,linux/arm64/v6,linux/arm64/v7,linux/arm64/v8
    #     tags: finwo/adminer:latest,finwo/adminer:4,finwo/adminer:4.8,finwo/adminer:4.8.1

  # deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    # - name: Deploy webhook
      # run: 'curl -X POST --header "Authorization: Bearer ${{ secrets.SWARMPIT_TOKEN }}" --header "Content-Type: application/json" --header "Accept: application/json" "https://swarmpit.finwo.net/api/stacks/adminer/redeploy"'
