name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: finwo/adminer:latest

  # deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    # - name: Deploy webhook
      # run: 'curl -X POST --header "Authorization: Bearer ${{ secrets.SWARMPIT_TOKEN }}" --header "Content-Type: application/json" --header "Accept: application/json" "https://swarmpit.finwo.net/api/stacks/adminer/redeploy"'
